# Generated by Django 2.2 on 2020-01-13 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStartup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=254)),
                ('Domains_Covered', models.CharField(max_length=300)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'About Startup',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=13)),
                ('role', models.CharField(max_length=254)),
                ('status', models.CharField(choices=[('MENTOR', 'MENTOR/INVESTOR'), ('COFOUNDER', 'COFOUNDER'), ('EXPLORER', 'EXPLORER')], default='EXPLORER', max_length=200)),
                ('startup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup', to='superapp.AboutStartup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartupGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('users', models.ManyToManyField(to='superapp.UserProfile')),
            ],
        ),
    ]
