# Generated by Django 2.2 on 2020-01-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=84)),
                ('description', models.CharField(max_length=255)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorname', to='superapp.UserProfile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupname', to='superapp.StartupGroup')),
            ],
        ),
    ]
